#include <iostream>
#include <fstream>
#include <string>
#include <cmath>
#include "matrix_creation/triangle/FEMTriangles.hpp"
#include "matrix_creation/rectangle/FEMRectangles.hpp"
#include "common/init/InitFuncs.hpp"
#include "common/classes/mesh/Point.hpp"
#include "common/classes/contribution_matrix/RectangleContributionMatrix.hpp"
#include "common/classes/contribution_matrix/TriangleContributionMatrix.hpp"
#include "common/classes/contribution_matrix/RectangleRightPart.hpp"
#include "common/classes/contribution_matrix/TriangleRightPart.hpp"
#include "common/classes/system/SystemParameters.hpp"
#include "libs/single_include/nlohmann/json.hpp"
#include "solvers/gauss/GaussSystemSolver.hpp"