all:
	g++ main.cpp \
	common/src/basicFuncs.cpp \
	matrix_creation/triangle/hLinear.cpp \
	matrix_creation/triangle/hConst.cpp \
	matrix_creation/rectangle/RectangleLinear.cpp \
	solvers/gauss/gaussFuncs.cpp \
	-o fem_reynolds.out
	./fem_reynolds.out
